name: Contribution Graph Action

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate contributions
        uses: your-username/github-contribution-graph-action@main # Use your forked repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BACKFILL: true # Add commits for past dates
          SKIP_WEEKENDS: true # Skip commits on weekends
